apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  # local:
  #   push: false 
  googleCloudBuild:
    projectId: ticketing-dev-362117
  artifacts:
    - image: us.gcr.io/ticketing-dev-362117/auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-dev-362117/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-dev-362117/orders
      context: orders
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-dev-362117/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-dev-362117/payments
      context: payments
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .