name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'
      
env:
  GKE_CLUSTER: ticketing-dev    # TODO: update to cluster name
  GKE_ZONE: southamerica-west1-a	   # TODO: update to cluster zone

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd orders && docker build -t adriantepes/orders .
      - run: docker push adriantepes/orders
      
      # Authentication via credentials json
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      # Get the GKE credentials so we can deploy to the cluster
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - run: kubectl rollout restart deployment orders-deploy