name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'
      

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && npm install
      - run: cd payments && npm install && npm run test:ci